name: Build and Publish PDF

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the `main` branch
  workflow_dispatch:  # Allow manual triggering from the Actions tab

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up LaTeX environment
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full biber

      # Step 3: Make `compile.sh` executable and run it
      - name: Compile LaTeX document with custom script
        run: |
          chmod +x ./compile.sh
          ./compile.sh

      # Step 4: Copy the PDF to a temporary directory
      - name: Prepare PDF for deployment
        run: |
          mkdir output
          mv notes.pdf output/

      # Step 5: Deploy the PDF to the `pdf` branch
      - name: Deploy to PDF branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf   # Specify the branch to publish to
          publish_dir: output   # Only deploy the output directory
          force_orphan: true    # Use an orphan branch for clean publishing
          keep_files: false     # Replace existing files in the branch
          commit_message: "Update notes.pdf"